app/Django_Reservation_System/core/urls.py
from django.urls import path

from . import views

app_name = "core"
urlpatterns = [
    path("register", views.RegisterUserForm.as_view(), name="register_admin"),
    path("dashboard/<slug>", views.ProfileView.as_view(), name="profile"),
    path("", views.HomeView.as_view(), name="home"),
    path("activate/<uidb64>/<token>/", views.activate, name="activation", ),
    path("login/", views.SimpleLoginPage.as_view(), name="login"),
    path("logout/", views.SimpleLogoutView.as_view(), name="logout"),
    path(
        "dashboard/<slug>/companyregistration",
        views.RegisterCompanyView.as_view(),
        name="register_company",
    ),
    path(
        "dashboard/<slug>/premisesregistration",
        views.RegisterPremisesView.as_view(),
        name="register_premises",
    ),
]

app/Django_Reservation_System/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Django_Reservation_System.core.urls', namespace='core')),
]

app/Django_Reservation_System/core/models.py
"""
Core models
"""
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


class Days(models.Model):
    day = models.CharField(max_length=9)

    def __str__(self):
        return self.day


class Profile(models.Model):
    """
    Model for company admins of reservation system
    """

    user = models.OneToOneField(User, on_delete=models.CASCADE)

    class Meta:
        permissions = [
            ("create_company", "Can create company"),
            ("edit_company", "Can edit company"),
            ("remove_company", "Can remove company"),
        ]

    def get_absolute_url(self):
        return reverse("products:product", kwargs={"slug": self.user.username})

    def __str__(self):
        return "%s %s" % (self.user.first_name, self.user.last_name)


class Worker(models.Model):
    """
    Model for worker
    """

    profile = models.OneToOneField(Profile, on_delete=models.CASCADE)

    def __str__(self):
        return "%s %s" % (self.profile.user.first_name, self.profile.user.last_name)


class Company(models.Model):
    """
    Model for company informations
    """

    id = models.AutoField(primary_key=True)
    name = models.CharField("Company name", max_length=200)
    company_id = models.IntegerField("Company registration number")
    vat = models.CharField("Vat number", max_length=15)
    address1 = models.CharField("Address line 1", max_length=1024,)
    address2 = models.CharField("Address line 2", max_length=1024,)
    zip_code = models.CharField("ZIP / Postal code", max_length=6,)
    city = models.CharField("City", max_length=1024,)
    country = models.CharField("Country", max_length=30,)
    owner = models.ManyToManyField(Profile)

    def __str__(self):
        return "%s" % self.name


class Premises(models.Model):
    """
    Model for companies premises
    """

    id = models.AutoField(primary_key=True)
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    name = models.CharField("Premises name", max_length=200)
    site_name = models.CharField("Site name", max_length=20, unique=True)
    working_days = models.ManyToManyField(Days)
    worker = models.ManyToManyField(Worker, blank=True)
    premises_type = models.CharField("Premises type", max_length=50)

    def __str__(self):
        return "%s" % self.name


class Holydays(models.Model):
    """
    Model for Workers holydays
    """

    worker = models.ForeignKey(Worker, on_delete=models.CASCADE)
    date_from = models.DateField("Date From")
    date_to = models.DateField("Date To")
    time_from = models.TimeField("Time From", null=True, blank=True)
    time_to = models.TimeField("Time To", null=True, blank=True)


class WorkingTime(models.Model):
    """
    Default working days and hours for Premises and Workers
    """

    premise = models.ForeignKey(Premises, on_delete=models.CASCADE, blank=True)
    worker = models.ForeignKey(Worker, on_delete=models.CASCADE, blank=True, null=True)
    valid_from = models.DateField("Valid From")
    valid_to = models.DateField("Valid To")
    opening_hours = models.TimeField()
    closing_hours = models.TimeField()


class DefaultServices(models.Model):
    name = models.CharField("Service name", max_length=30)
    description = models.TextField("Service description")
    price = models.FloatField("Service price")


class Services(DefaultServices, models.Model):
    """
    Services for every premises
    """

    premises = models.ForeignKey(Premises, on_delete=models.CASCADE)
    worker = models.ManyToManyField(Worker, blank=True)

app/Django_Reservation_System/core/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.forms import ModelForm, CheckboxSelectMultiple, BaseModelFormSet, Form
from django import forms
from .models import Profile, Company, Premises, Days


class UserRegistration(UserCreationForm):
    """
    Form for registering new users
    """

    class Meta:
        model = User
        fields = (
            "username",
            "password1",
            "password2",
            "email",
            "first_name",
            "last_name",
        )


class SimpleLoginForm(AuthenticationForm):
    """
    SimpleLoginForm is equal to default AuthenticationForm
    """


class CompanyRegistration(ModelForm):
    """
    Form for creating new company under user
    """

    class Meta:
        model = Company
        fields = [
            "name",
            "vat",
            "company_id",
            "address1",
            "address2",
            "zip_code",
            "city",
            "country",
        ]


class PremisesRegistration(ModelForm):
    """
    Form for creating Premises
    """

    def __init__(self, *args, **kwargs):
        current_user = kwargs.get("user")
        super().__init__(*args, **kwargs)
        self.fields["company"].queryset = Company.objects.filter(owner=current_user)

    class Meta:
        model = Premises
        fields = "__all__"
        widgets = {"working_days": CheckboxSelectMultiple}

app/Django_Reservation_System/core/views.py
import random, datetime
from django.shortcuts import redirect, HttpResponse, reverse
from django.contrib.auth import login
from .forms import (
    UserRegistration,
    SimpleLoginForm,
    CompanyRegistration,
    PremisesRegistration,
)
from django.views.generic.edit import CreateView
from django.views.generic import DetailView, TemplateView
from django.core.mail import EmailMessage
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import (
    urlsafe_base64_encode,
    urlsafe_base64_decode,
    url_has_allowed_host_and_scheme,
)
from django.template.loader import render_to_string
from .token import account_activation_token
from .models import Profile, Worker, WorkingTime
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User


class RegisterUserForm(CreateView):
    form_class = UserRegistration
    template_name = "core/RegisterUser.html"
    success_url = "core:home"

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        self.object = None
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            person = Profile.objects.create(user=user)
            person.save()
            current_site = get_current_site(request)
            mail_subject = "Activate your blog account."
            message = render_to_string(
                "acc_active_email.html",
                {
                    "user": user,
                    "domain": current_site.domain,
                    "uid": urlsafe_base64_encode(force_bytes(user.pk)),
                    "token": account_activation_token.make_token(user),
                },
            )
            to_email = form.cleaned_data.get("email")
            email = EmailMessage(mail_subject, message, to=[to_email])
            email.send()
            return HttpResponseRedirect(reverse("core:home"))
        else:
            return self.form_invalid(form)


def activate(request, uidb64, token):
    try:
        uid = urlsafe_base64_decode(uidb64)
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
        return HttpResponse("User None!")
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        return redirect("core:profile", user.username)
    else:
        return HttpResponse("Activation lk s invalid!")


class ProfileView(LoginRequiredMixin, UserPassesTestMixin, DetailView):
    login_url = "core:login"
    redirect_field_name = "redirect_to"
    model = User
    slug_field = "username"
    template_name = "core/profile.html"

    def test_func(self):
        return self.request.user.username == self.kwargs["slug"]


class SimpleLoginPage(LoginView):
    template_name = "core/primitive-login-page.html"
    authentication_form = SimpleLoginForm
    redirect_authenticated_user = False

    def get_redirect_url(self):
        try:
            username = self.request.user.username
            redirect_to = "/dashboard/" + username  # upravit
            return redirect_to
        finally:
            super().get_redirect_url()


class HomeView(TemplateView):
    template_name = "core/home.html"


class SimpleLogoutView(LogoutView):
    next_page = "core:home"


class RegisterCompanyView(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    login_url = "core:login"
    slug_field = "username"
    template_name = "core/RegisterCompany.html"
    form_class = CompanyRegistration

    def test_func(self):
        return self.request.user.username == self.kwargs["slug"]

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        self.object = None
        if form.is_valid():
            company = form.save(commit=False)
            company.save()
            profile = request.user.profile
            company.owner.add(profile)
            return HttpResponseRedirect(
                reverse("core:profile", args=[request.user.username])
            )
        else:
            return self.form_invalid(form)


class RegisterPremisesView(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    login_url = "core:login"
    slug_field = "username"
    template_name = "core/RegisterPremises.html"
    form_class = PremisesRegistration

    def test_func(self):
        return self.request.user.username == self.kwargs["slug"]

    def handle_no_permission(self):
        return redirect("core:login")

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        self.object = None
        if form.is_valid():
            premises = form.save(commit=False)
            premises.save()
            for day in form.cleaned_data.get("working_days"):
                premises.working_days.add(day)
            first_name_list = request.POST.getlist("first_name")
            last_name_list = request.POST.getlist("last_name")
            for x, first_name in enumerate(first_name_list):
                last_name = last_name_list[x]
                random_username = (
                    first_name + last_name + str(random.randint(1, 100000000))
                )
                user = User.objects.create_user(
                    first_name=first_name, last_name=last_name, username=random_username
                )
                user.is_active = False
                user.save()
                person = Profile.objects.create(user=user)
                person.save()
                worker = Worker.objects.create(profile=person)
                worker.save()
                premises.worker.add(worker)
                times = WorkingTime.objects.create(
                    premise=premises,
                    worker=None,
                    valid_from=datetime.date.today(),
                    valid_to=datetime.date(2999, 12, 1),
                    opening_hours=request.POST.get("opening_time"),
                    closing_hours=request.POST.get("closing_time"),
                )
            return HttpResponseRedirect(
                reverse("core:profile", args=[request.user.username])
            )
        else:
            return self.form_invalid(form)

app/Django_Reservation_System/core/templates/core/RegisterCompany.html
{% extends 'core/dashboard-base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <div class="container">
      <div class="row justify-content-center">
        <div class="col-md-5">
          <h2 class="mt-3 text-center">Sign up form</h2>
          <hr class="mt-2 mb-4">
            <form method="post" novalidate>
                {% csrf_token %}
                {{ form|crispy }}
                <div class="text-center">
                    <button type="submit" class="btn btn-primary">Sign up</button>
                </div>
            </form>
        </div>
      </div>
  </div>
{% endblock %}

app/Django_Reservation_System/core/templates/core/RegisterPremises.html
{% extends 'core/dashboard-base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <div class="container">
      <div class="row justify-content-center">
        <div class="col-md-8">
          <h2 class="mt-5 text-center">Register Premises</h2>
          <hr class="mt-4 mb-4">
            <form method="post" novalidate>
                {% csrf_token %}
                {{ form.company|as_crispy_field}}
                {{ form.name|as_crispy_field}}
                {{ form.site_name|as_crispy_field}}
                {{ form.premises_type|as_crispy_field }}
                <div id="div_id_opening_hours" class="form-group">
                <label for="" class=" requiredField">
                Opening Hours<span class="asteriskField">*</span>
                </label>
                    <div class="form-row">
                        <div class="form-group form-inline">
                        <label class="mx-2">Opening Time</label>
                        <input type="time" class="form-control timelist" name="opening_time" id="opening_time">
                        </div>
                        <div class="form-group form-inline" >
                        <label class="ml-5 mr-2 form-label">Closing Time</label>
                        <input type="time" class="form-control timelist" name="closing_time" id="closing_time">
                        </div>
                    </div>
                </div>
                <div id="div_id_working_days" class="form-group">
                <label for="" class=" requiredField">
                Working days<span class="asteriskField">*</span>
                </label>
                    <div class="">
                    {% for value, text in form.working_days.field.choices %}

                        <div class="form-check form-check-inline">
                        <input type="checkbox" class="form-check-input" name="working_days" id="id_working_days_'{{ value }}'" value={{ value }}>
                        <label class="form-check-label" for="id_working_days_'{{ value }}'">{{ text }}</label>
                        </div>

                    {% endfor %}
                    </div>
                </div>
                <div id="div_id_site_name" class="form-group">
                    <label for="id_worker_name" class=" requiredField">
                        Worker Name<span class="asteriskField">*</span>
                    </label>
                    <div class="form-group">
                <div class="form-row">
                    <div class="col">
                        <input type="text" class="form-control" id="first1" placeholder="First name" name="first_name">
                    </div>
                    <div class="col">
                        <input type="text" class="form-control" id="last1" placeholder="Last name" name="last_name">
                    </div>
                    <div class="input-group-btn">
                        <button class="btn btn-success" type="button"  onclick="education_fields();">+</button>
                    </div>
                </div>
                </div >
                <div id="education_fields"></div>
                </div>
                <div class="text-center">
                    <button type="submit" class="btn btn-primary">Register</button>
                </div>
            </form>
        </div>
      </div>
  </div>

    <script type="text/javascript">
    var room = 1;
    function education_fields() {
    room++;
    var objTo = document.getElementById('education_fields')
    var divtest = document.createElement("div");
	divtest.setAttribute("class", "form-group removeclass"+room);
	var rdiv = 'removeclass'+room;
    divtest.innerHTML = '<div class="form-row"><div class="col"><input type="text" class="form-control" id="first'+ room +'" placeholder="First name" name="first_name"></div><div class="col"><input type="text" class="form-control" id="last'+ room +'" placeholder="Last name" name="last_name"></div><div class="input-group-btn"><button class="btn btn-danger" type="button" onclick="remove_education_fields('+ room +');">-</button></div><div class="clear"></div>';
    objTo.appendChild(divtest)
   }
   function remove_education_fields(rid) {
	   $('.removeclass'+rid).remove();
   }
</script>

{% endblock %}

app/Django_Reservation_System/core/templates/core/RegisterUser.html
{% extends 'core/base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <div class="container">
      <div class="row justify-content-center">
        <div class="col-md-5">
          <h2 class="mt-3 text-center">Sign up form</h2>
          <hr class="mt-2 mb-4">
            <form method="post" novalidate>
                {% csrf_token %}
                {{ form|crispy }}
                <div class="text-center">
                    <button type="submit" class="btn btn-primary">Sign up</button>
                </div>
            </form>
        </div>
      </div>
  </div>
{% endblock %}

app/Django_Reservation_System/core/templates/core/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <title>Rezervuj sa</title>
    <link rel="shortcut icon" type="image/png" href="https://cdn4.iconfinder.com/data/icons/small-n-flat/24/calendar-512.png">
  </head>
  <body>
    {%  include 'core/menu.html' %}
    {% block content %}
    {% endblock %}
  </body>
</html>

app/Django_Reservation_System/core/templates/core/dashboard-bar.html
<nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
  <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="{% url "core:profile" slug=user.username %}">{{ user.profile }}</a>
  <ul class="navbar-nav px-3">
    <li class="nav-item text-nowrap">
      <a class="nav-link" href="{% url 'core:logout' %}">Sign out</a>
    </li>
  </ul>
</nav>

app/Django_Reservation_System/core/templates/core/dashboard-base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <title>Rezervuj sa</title>
    <link href="https://getbootstrap.com/docs/4.4/examples/dashboard/dashboard.css" rel="stylesheet">
    <link rel="shortcut icon" href="https://github.com/nhn/tui.calendar/blob/master/examples/images/icon.png">
  </head>
  <body>
    {%  include 'core/dashboard-bar.html' %}
    <div class="container-fluid">
        <div class="row">
        {%  include 'core/dashboard-menu.html' %}
        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
        {% block content %}
        {% endblock %}
        </main>
        </div>
    </div>
  </body>
</html>

app/Django_Reservation_System/core/templates/core/dashboard-menu.html
<nav class="col-md-2 d-none d-md-block bg-light sidebar">
      <div class="sidebar-sticky">
        <ul class="nav flex-column">
          <li class="nav-item">
            <a class="nav-link active" href="{% url "core:register_company" slug=user.username %}">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-home"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path><polyline points="9 22 9 12 15 12 15 22"></polyline></svg>
              Register Company <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url "core:register_premises" slug=user.username %}">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file"><path d="M13 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V9z"></path><polyline points="13 2 13 9 20 9"></polyline></svg>
              Register Premises
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-shopping-cart"><circle cx="9" cy="21" r="1"></circle><circle cx="20" cy="21" r="1"></circle><path d="M1 1h4l2.68 13.39a2 2 0 0 0 2 1.61h9.72a2 2 0 0 0 2-1.61L23 6H6"></path></svg>
              Products
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-users"><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path><circle cx="9" cy="7" r="4"></circle><path d="M23 21v-2a4 4 0 0 0-3-3.87"></path><path d="M16 3.13a4 4 0 0 1 0 7.75"></path></svg>
              Customers
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-bar-chart-2"><line x1="18" y1="20" x2="18" y2="10"></line><line x1="12" y1="20" x2="12" y2="4"></line><line x1="6" y1="20" x2="6" y2="14"></line></svg>
              Reports
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-layers"><polygon points="12 2 2 7 12 12 22 7 12 2"></polygon><polyline points="2 17 12 22 22 17"></polyline><polyline points="2 12 12 17 22 12"></polyline></svg>
              Integrations
            </a>
          </li>
        </ul>

        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
          <span>Saved reports</span>
          <a class="d-flex align-items-center text-muted" href="#" aria-label="Add a new report">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-plus-circle"><circle cx="12" cy="12" r="10"></circle><line x1="12" y1="8" x2="12" y2="16"></line><line x1="8" y1="12" x2="16" y2="12"></line></svg>
          </a>
        </h6>
        <ul class="nav flex-column mb-2">
          <li class="nav-item">
            <a class="nav-link" href="#">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file-text"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path><polyline points="14 2 14 8 20 8"></polyline><line x1="16" y1="13" x2="8" y2="13"></line><line x1="16" y1="17" x2="8" y2="17"></line><polyline points="10 9 9 9 8 9"></polyline></svg>
              Current month
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file-text"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path><polyline points="14 2 14 8 20 8"></polyline><line x1="16" y1="13" x2="8" y2="13"></line><line x1="16" y1="17" x2="8" y2="17"></line><polyline points="10 9 9 9 8 9"></polyline></svg>
              Last quarter
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file-text"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path><polyline points="14 2 14 8 20 8"></polyline><line x1="16" y1="13" x2="8" y2="13"></line><line x1="16" y1="17" x2="8" y2="17"></line><polyline points="10 9 9 9 8 9"></polyline></svg>
              Social engagement
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file-text"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path><polyline points="14 2 14 8 20 8"></polyline><line x1="16" y1="13" x2="8" y2="13"></line><line x1="16" y1="17" x2="8" y2="17"></line><polyline points="10 9 9 9 8 9"></polyline></svg>
              Year-end sale
            </a>
          </li>
        </ul>
      </div>
    </nav>

app/Django_Reservation_System/core/templates/core/home.html
{% extends 'core/base.html' %}

{% load crispy_forms_tags %}

{% block content %}
{% endblock %}

app/Django_Reservation_System/core/templates/core/profile.html
{% extends 'core/dashboard-base.html' %}

{% block content %}
<h2>User Detail</h2>
<p>{{ object.first_name }}</p>
<p>{{ object.last_name }}</p>
<p><a href= {% url "core:logout" %}> Logout </a> </p>
{% endblock %}